# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/JTZ_DL/MAC-Yee

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/JTZ_DL/MAC-Yee

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/JTZ_DL/MAC-Yee/CMakeFiles /home/JTZ_DL/MAC-Yee//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/JTZ_DL/MAC-Yee/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/JTZ_DL/MAC-Yee/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DUAL_MAC

# Build rule for target.
DUAL_MAC: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DUAL_MAC
.PHONY : DUAL_MAC

# fast build rule for target.
DUAL_MAC/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC.dir/build.make CMakeFiles/DUAL_MAC.dir/build
.PHONY : DUAL_MAC/fast

#=============================================================================
# Target rules for targets named DUAL_MAC_TEST

# Build rule for target.
DUAL_MAC_TEST: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DUAL_MAC_TEST
.PHONY : DUAL_MAC_TEST

# fast build rule for target.
DUAL_MAC_TEST/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC_TEST.dir/build.make CMakeFiles/DUAL_MAC_TEST.dir/build
.PHONY : DUAL_MAC_TEST/fast

src/1form_assemble_matrix.o: src/1form_assemble_matrix.cpp.o
.PHONY : src/1form_assemble_matrix.o

# target to build an object file
src/1form_assemble_matrix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC.dir/build.make CMakeFiles/DUAL_MAC.dir/src/1form_assemble_matrix.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC_TEST.dir/build.make CMakeFiles/DUAL_MAC_TEST.dir/src/1form_assemble_matrix.cpp.o
.PHONY : src/1form_assemble_matrix.cpp.o

src/1form_assemble_matrix.i: src/1form_assemble_matrix.cpp.i
.PHONY : src/1form_assemble_matrix.i

# target to preprocess a source file
src/1form_assemble_matrix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC.dir/build.make CMakeFiles/DUAL_MAC.dir/src/1form_assemble_matrix.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC_TEST.dir/build.make CMakeFiles/DUAL_MAC_TEST.dir/src/1form_assemble_matrix.cpp.i
.PHONY : src/1form_assemble_matrix.cpp.i

src/1form_assemble_matrix.s: src/1form_assemble_matrix.cpp.s
.PHONY : src/1form_assemble_matrix.s

# target to generate assembly for a file
src/1form_assemble_matrix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC.dir/build.make CMakeFiles/DUAL_MAC.dir/src/1form_assemble_matrix.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC_TEST.dir/build.make CMakeFiles/DUAL_MAC_TEST.dir/src/1form_assemble_matrix.cpp.s
.PHONY : src/1form_assemble_matrix.cpp.s

src/2form_assemble_matrix.o: src/2form_assemble_matrix.cpp.o
.PHONY : src/2form_assemble_matrix.o

# target to build an object file
src/2form_assemble_matrix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC.dir/build.make CMakeFiles/DUAL_MAC.dir/src/2form_assemble_matrix.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC_TEST.dir/build.make CMakeFiles/DUAL_MAC_TEST.dir/src/2form_assemble_matrix.cpp.o
.PHONY : src/2form_assemble_matrix.cpp.o

src/2form_assemble_matrix.i: src/2form_assemble_matrix.cpp.i
.PHONY : src/2form_assemble_matrix.i

# target to preprocess a source file
src/2form_assemble_matrix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC.dir/build.make CMakeFiles/DUAL_MAC.dir/src/2form_assemble_matrix.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC_TEST.dir/build.make CMakeFiles/DUAL_MAC_TEST.dir/src/2form_assemble_matrix.cpp.i
.PHONY : src/2form_assemble_matrix.cpp.i

src/2form_assemble_matrix.s: src/2form_assemble_matrix.cpp.s
.PHONY : src/2form_assemble_matrix.s

# target to generate assembly for a file
src/2form_assemble_matrix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC.dir/build.make CMakeFiles/DUAL_MAC.dir/src/2form_assemble_matrix.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC_TEST.dir/build.make CMakeFiles/DUAL_MAC_TEST.dir/src/2form_assemble_matrix.cpp.s
.PHONY : src/2form_assemble_matrix.cpp.s

src/evaluation.o: src/evaluation.cpp.o
.PHONY : src/evaluation.o

# target to build an object file
src/evaluation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC.dir/build.make CMakeFiles/DUAL_MAC.dir/src/evaluation.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC_TEST.dir/build.make CMakeFiles/DUAL_MAC_TEST.dir/src/evaluation.cpp.o
.PHONY : src/evaluation.cpp.o

src/evaluation.i: src/evaluation.cpp.i
.PHONY : src/evaluation.i

# target to preprocess a source file
src/evaluation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC.dir/build.make CMakeFiles/DUAL_MAC.dir/src/evaluation.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC_TEST.dir/build.make CMakeFiles/DUAL_MAC_TEST.dir/src/evaluation.cpp.i
.PHONY : src/evaluation.cpp.i

src/evaluation.s: src/evaluation.cpp.s
.PHONY : src/evaluation.s

# target to generate assembly for a file
src/evaluation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC.dir/build.make CMakeFiles/DUAL_MAC.dir/src/evaluation.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC_TEST.dir/build.make CMakeFiles/DUAL_MAC_TEST.dir/src/evaluation.cpp.s
.PHONY : src/evaluation.cpp.s

src/lifecycle.o: src/lifecycle.cpp.o
.PHONY : src/lifecycle.o

# target to build an object file
src/lifecycle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC.dir/build.make CMakeFiles/DUAL_MAC.dir/src/lifecycle.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC_TEST.dir/build.make CMakeFiles/DUAL_MAC_TEST.dir/src/lifecycle.cpp.o
.PHONY : src/lifecycle.cpp.o

src/lifecycle.i: src/lifecycle.cpp.i
.PHONY : src/lifecycle.i

# target to preprocess a source file
src/lifecycle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC.dir/build.make CMakeFiles/DUAL_MAC.dir/src/lifecycle.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC_TEST.dir/build.make CMakeFiles/DUAL_MAC_TEST.dir/src/lifecycle.cpp.i
.PHONY : src/lifecycle.cpp.i

src/lifecycle.s: src/lifecycle.cpp.s
.PHONY : src/lifecycle.s

# target to generate assembly for a file
src/lifecycle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC.dir/build.make CMakeFiles/DUAL_MAC.dir/src/lifecycle.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC_TEST.dir/build.make CMakeFiles/DUAL_MAC_TEST.dir/src/lifecycle.cpp.s
.PHONY : src/lifecycle.cpp.s

src/linearsolver.o: src/linearsolver.cpp.o
.PHONY : src/linearsolver.o

# target to build an object file
src/linearsolver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC.dir/build.make CMakeFiles/DUAL_MAC.dir/src/linearsolver.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC_TEST.dir/build.make CMakeFiles/DUAL_MAC_TEST.dir/src/linearsolver.cpp.o
.PHONY : src/linearsolver.cpp.o

src/linearsolver.i: src/linearsolver.cpp.i
.PHONY : src/linearsolver.i

# target to preprocess a source file
src/linearsolver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC.dir/build.make CMakeFiles/DUAL_MAC.dir/src/linearsolver.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC_TEST.dir/build.make CMakeFiles/DUAL_MAC_TEST.dir/src/linearsolver.cpp.i
.PHONY : src/linearsolver.cpp.i

src/linearsolver.s: src/linearsolver.cpp.s
.PHONY : src/linearsolver.s

# target to generate assembly for a file
src/linearsolver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC.dir/build.make CMakeFiles/DUAL_MAC.dir/src/linearsolver.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC_TEST.dir/build.make CMakeFiles/DUAL_MAC_TEST.dir/src/linearsolver.cpp.s
.PHONY : src/linearsolver.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC.dir/build.make CMakeFiles/DUAL_MAC.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC.dir/build.make CMakeFiles/DUAL_MAC.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC.dir/build.make CMakeFiles/DUAL_MAC.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/output.o: src/output.cpp.o
.PHONY : src/output.o

# target to build an object file
src/output.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC.dir/build.make CMakeFiles/DUAL_MAC.dir/src/output.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC_TEST.dir/build.make CMakeFiles/DUAL_MAC_TEST.dir/src/output.cpp.o
.PHONY : src/output.cpp.o

src/output.i: src/output.cpp.i
.PHONY : src/output.i

# target to preprocess a source file
src/output.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC.dir/build.make CMakeFiles/DUAL_MAC.dir/src/output.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC_TEST.dir/build.make CMakeFiles/DUAL_MAC_TEST.dir/src/output.cpp.i
.PHONY : src/output.cpp.i

src/output.s: src/output.cpp.s
.PHONY : src/output.s

# target to generate assembly for a file
src/output.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC.dir/build.make CMakeFiles/DUAL_MAC.dir/src/output.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC_TEST.dir/build.make CMakeFiles/DUAL_MAC_TEST.dir/src/output.cpp.s
.PHONY : src/output.cpp.s

src/setup.o: src/setup.cpp.o
.PHONY : src/setup.o

# target to build an object file
src/setup.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC.dir/build.make CMakeFiles/DUAL_MAC.dir/src/setup.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC_TEST.dir/build.make CMakeFiles/DUAL_MAC_TEST.dir/src/setup.cpp.o
.PHONY : src/setup.cpp.o

src/setup.i: src/setup.cpp.i
.PHONY : src/setup.i

# target to preprocess a source file
src/setup.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC.dir/build.make CMakeFiles/DUAL_MAC.dir/src/setup.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC_TEST.dir/build.make CMakeFiles/DUAL_MAC_TEST.dir/src/setup.cpp.i
.PHONY : src/setup.cpp.i

src/setup.s: src/setup.cpp.s
.PHONY : src/setup.s

# target to generate assembly for a file
src/setup.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC.dir/build.make CMakeFiles/DUAL_MAC.dir/src/setup.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC_TEST.dir/build.make CMakeFiles/DUAL_MAC_TEST.dir/src/setup.cpp.s
.PHONY : src/setup.cpp.s

src/time_evolve.o: src/time_evolve.cpp.o
.PHONY : src/time_evolve.o

# target to build an object file
src/time_evolve.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC.dir/build.make CMakeFiles/DUAL_MAC.dir/src/time_evolve.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC_TEST.dir/build.make CMakeFiles/DUAL_MAC_TEST.dir/src/time_evolve.cpp.o
.PHONY : src/time_evolve.cpp.o

src/time_evolve.i: src/time_evolve.cpp.i
.PHONY : src/time_evolve.i

# target to preprocess a source file
src/time_evolve.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC.dir/build.make CMakeFiles/DUAL_MAC.dir/src/time_evolve.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC_TEST.dir/build.make CMakeFiles/DUAL_MAC_TEST.dir/src/time_evolve.cpp.i
.PHONY : src/time_evolve.cpp.i

src/time_evolve.s: src/time_evolve.cpp.s
.PHONY : src/time_evolve.s

# target to generate assembly for a file
src/time_evolve.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC.dir/build.make CMakeFiles/DUAL_MAC.dir/src/time_evolve.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC_TEST.dir/build.make CMakeFiles/DUAL_MAC_TEST.dir/src/time_evolve.cpp.s
.PHONY : src/time_evolve.cpp.s

test/main.o: test/main.cpp.o
.PHONY : test/main.o

# target to build an object file
test/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC_TEST.dir/build.make CMakeFiles/DUAL_MAC_TEST.dir/test/main.cpp.o
.PHONY : test/main.cpp.o

test/main.i: test/main.cpp.i
.PHONY : test/main.i

# target to preprocess a source file
test/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC_TEST.dir/build.make CMakeFiles/DUAL_MAC_TEST.dir/test/main.cpp.i
.PHONY : test/main.cpp.i

test/main.s: test/main.cpp.s
.PHONY : test/main.s

# target to generate assembly for a file
test/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DUAL_MAC_TEST.dir/build.make CMakeFiles/DUAL_MAC_TEST.dir/test/main.cpp.s
.PHONY : test/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... DUAL_MAC"
	@echo "... DUAL_MAC_TEST"
	@echo "... src/1form_assemble_matrix.o"
	@echo "... src/1form_assemble_matrix.i"
	@echo "... src/1form_assemble_matrix.s"
	@echo "... src/2form_assemble_matrix.o"
	@echo "... src/2form_assemble_matrix.i"
	@echo "... src/2form_assemble_matrix.s"
	@echo "... src/evaluation.o"
	@echo "... src/evaluation.i"
	@echo "... src/evaluation.s"
	@echo "... src/lifecycle.o"
	@echo "... src/lifecycle.i"
	@echo "... src/lifecycle.s"
	@echo "... src/linearsolver.o"
	@echo "... src/linearsolver.i"
	@echo "... src/linearsolver.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/output.o"
	@echo "... src/output.i"
	@echo "... src/output.s"
	@echo "... src/setup.o"
	@echo "... src/setup.i"
	@echo "... src/setup.s"
	@echo "... src/time_evolve.o"
	@echo "... src/time_evolve.i"
	@echo "... src/time_evolve.s"
	@echo "... test/main.o"
	@echo "... test/main.i"
	@echo "... test/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/JTZ_DL/MAC-Yee/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

